import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'lenis/dist/lenis.css'
import NavBar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import ModalProvider from "@/context/modalProvider";
import Middleware from "@/components/middleware/middleware";
import ScrollProvider from "@/components/layout/scrollProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ModalProvider>
      <ScrollProvider>
        <html lang="en" className="dark">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center justify-start min-w-screen min-h-screen bg-black `}
          >
            <NavBar/>
            <Middleware>
              {children}
            </Middleware>
            <Footer/>
          </body>
        </html>
    </ScrollProvider>
    </ModalProvider>
  );
}
